[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  timeout = 26

[[redirects]]
  from = "/api/enrich"
  to = "/.netlify/functions/enrich"
  status = 200
